services:
  bakery: # Servicio de la API de la pasteleria OnlyFlans
    build: # Construcci贸n de la imagen
      context: . # Contexto de construcci贸n
      dockerfile: Dockerfile # Dockerfile a utilizar
    container_name: bakery_app # Nombre del contenedor
    ports: # Puertos a exponer
      - "80:8080"
    command: ["java", "-jar", "/app/app.jar"] # Comando para ejecutar la aplicaci贸n

    env_file:
      - .env

    networks:
      - bakery_network # Red personalizada

networks:
  bakery_network: # Definici贸n de la red personalizada
    driver: bridge